### ISSUE TITLE
"How-to guides" solutions

### ISSUE THREAD

**Issue by nilgoyette** [odoo/tutorials#64]
I see that this repo contains the solutions for several projects in "Tutorials" but I can't find the solutions for the "How-to guides". Are they here? If not, do you plan to add them?

I'm trying to [Create a standalone Owl application](https://www.odoo.com/documentation/17.0/developer/howtos/standalone_owl_application.html), and I'm failing so far. Maybe because sections 3 and 4 are unclear on where to put the files, or maybe for some other reasons, it's hard to tell. With a working solution, I could concentrate on coding my project instead of wondering why I kept getting a 404 on `http://localhost:8069/imeka/standalone_app`, or later when I found the problem `AttributeError: 'Request' object has no attribute 'website'`.

**Comment by AntoineVDV** [comment]
Hi @nilgoyette, it is not planned to add solutions for how-to guides because this type of documentation is meant to give the *generic* recipe for common problems, not guide the user through a series of exercises.

However, if you find something wrong in the documentation, make sure to open an issue on the odoo/documentation repository or, even better, a PR! ;)
